[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Davfl solutions for Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.1",
    "typer>=0.20.0",
]
